#!/usr/bin/env python3
"""
build.py — embed all content/*.md files into content-data.js
Run this after editing any markdown file:  python3 build.py
"""
import os, json

content_dir = os.path.join(os.path.dirname(__file__), "content")
output_file = os.path.join(os.path.dirname(__file__), "content-data.js")

data = {}
for fname in sorted(os.listdir(content_dir)):
    if fname.endswith(".md"):
        path = os.path.join(content_dir, fname)
        with open(path, "r", encoding="utf-8") as f:
            data["content/" + fname] = f.read()

js = "// Auto-generated by build.py — do not edit manually\n"
js += "window.CONTENT_DATA = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n"

with open(output_file, "w", encoding="utf-8") as f:
    f.write(js)

print(f"✅  Built content-data.js ({len(data)} files)")
